Repository iiasa/message_ix, pull requests merged in 2019-06, with the labels that each got.

#161 Adding new years to a MESSAGE scenario
  RELEASE_NOTES.md
  doc/source/guide.rst
  doc/source/tools/add_year.rst
  message_ix/tools/__init__.py
  message_ix/tools/add_year/README.rst
  message_ix/tools/add_year/__init__.py
  message_ix/tools/add_year/__main__.py
  setup.py
  tests/tools/test_add_year.py
Labels: enhancement

#212 add tests that `firstmodelyear` is cloned correctly
  message_ix/testing.py
  tests/test_integration.py
Labels: bug

#209 Clean up documentation for 1.2
  .github/PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  doc/source/api/ixmp.rst
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
Labels: documentation
