Repository iiasa/message_ix, pull requests merged in 2019-10, with the labels that each got.

#232 Updating Westeros tutorials and adding new ones
  RELEASE_NOTES.md
  tests/test_tutorials.py
  tutorial/README.rst
  tutorial/utils/plotting.py
  tutorial/westeros/_static/cf_wind.png
  tutorial/westeros/_static/load_seasons.png
  tutorial/westeros/westeros_baseline.ipynb
  tutorial/westeros/westeros_emissions_bounds.ipynb
  tutorial/westeros/westeros_emissions_taxes.ipynb
  tutorial/westeros/westeros_firm_capacity.ipynb
  tutorial/westeros/westeros_flexible_generation.ipynb
  tutorial/westeros/westeros_seasonality.ipynb
Labels: documentation

#236 Improve message_ix reporting for message_data, part 1
  .gitignore
  RELEASE_NOTES.md
  doc/source/conf.py
  doc/source/reporting.rst
  message_ix/reporting/__init__.py
  message_ix/reporting/computations.py
  message_ix/reporting/pyam.py
  tests/test_reporting.py
Labels: enhancement, reporting

#235 Add reporting tutorial
  .travis.yml
  RELEASE_NOTES.md
  appveyor.yml
  setup.py
  tests/test_tutorials.py
  tutorial/.gitignore
  tutorial/README.rst
  tutorial/westeros/westeros_report.ipynb
Labels: documentation, reporting
