Repository iiasa/message_ix, pull requests merged in 2020-08, with the labels that each got.

#377 Clean up R tutorials, testing, and CI
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pytest.yml
  .gitignore
  INSTALL.rst
  RELEASE_NOTES.rst
  conftest.py
  doc/README.rst
  doc/source/api.rst
  doc/source/index.rst
  doc/source/rmessageix.rst
  install.bat
  message_ix/tests/test_tutorials.py
  rmessageix/.Rbuildignore
  rmessageix/DESCRIPTION
  rmessageix/NAMESPACE
  rmessageix/R/init_rmessageix.R
  rmessageix/README.md
  rmessageix/build_rmessageix.R
  rmessageix/man/rmessageix.Rd
  rmessageix/source/DESCRIPTION
  rmessageix/source/R/init_rmessageix.R
  rmessageix/source/inst/docum/.gitignore
  rmessageix/source/rmessageix.Rproj
  rmessageix/tests/testthat.R
  rmessageix/tests/testthat/test_core.R
  setup.cfg
  tutorial/Austrian_energy_system/R_austria.ipynb
  tutorial/Austrian_energy_system/R_austria_load_scenario.ipynb
  tutorial/README.rst
Labels: R, ci, docs

#286 Set duration_period in add_horizon()
  RELEASE_NOTES.rst
  doc/source/index.rst
  doc/source/time.rst
  message_ix/core.py
  message_ix/tests/test_core.py
  setup.cfg
Labels: enh

#382 cleanup inconsistency between in gams documentation and equation (OBJ)
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/model_core.gms
Labels: docs

#381 Fix Codecov status checks and Python 3.6 build
  .github/workflows/pytest.yml
  RELEASE_NOTES.rst
  message_ix/core.py
  message_ix/tests/test_core.py
Labels: ci

#389 Fix passthrough of reporting.pyam.concat() args
  RELEASE_NOTES.rst
  message_ix/reporting/pyam.py
  message_ix/testing/__init__.py
  message_ix/tests/test_core.py
  message_ix/tests/test_reporting.py
  message_ix/tools/add_year/README.rst
  message_ix/utils.py
  tutorial/Austrian_energy_system/austria.ipynb
  tutorial/westeros/westeros_baseline.ipynb
Labels: bug, reporting

#391 Add prerequisite knowledge page to docs
  INSTALL.rst
  README.md
  RELEASE_NOTES.rst
  doc/source/conf.py
  doc/source/framework.rst
  doc/source/index.rst
  doc/source/install.rst
  doc/source/prereqs.rst
  doc/source/rmessageix.rst
  tutorial/Austrian_energy_system/R_austria.ipynb
  tutorial/Austrian_energy_system/austria.ipynb
  tutorial/README.rst
  tutorial/westeros/westeros_baseline.ipynb
Labels: docs

#366 Westeros tutorial: Fossil resources
  RELEASE_NOTES.rst
  tutorial/README.rst
  tutorial/utils/plotting.py
  tutorial/westeros/westeros_fossil_resource.ipynb
Labels: docs

#392 Expand doc/source/contributing.rst
  CONTRIBUTING.rst
  RELEASE_NOTES.rst
  doc/source/contributing.rst
  doc/source/prereqs.rst
Labels: docs
