Repository iiasa/message_ix, pull requests merged in 2020-04, with the labels that each got.

#321 Transfer Excel data I/O to ixmp
  RELEASE_NOTES.rst
  doc/source/api.rst
  message_ix/core.py
  message_ix/tests/test_core.py
Labels: enh

#300 Documentation cleanup
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
Labels: docs

#332 Reporting improvements for 2020-W16
  .travis.yml
  doc/source/reporting.rst
  message_ix/reporting/__init__.py
  setup.cfg
Labels: reporting

#344 Exclude JPype1 0.7.3
  ci/conda-requirements.txt
Labels: ci

#343 Pass MESSAGE-MACRO convergence parameters through API
  RELEASE_NOTES.rst
  doc/source/api.rst
  message_ix/core.py
  message_ix/model/MESSAGE-MACRO_run.gms
  message_ix/models.py
  message_ix/tests/test_models.py
Labels: enh, macro
