Repository iiasa/message_ix, pull requests merged in 2021-05, with the labels that each got.

#473 Update docs for v3.3.0; remove rmessageix
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
  .gitignore
  INSTALL.rst
  RELEASE_NOTES.rst
  doc/conf.py
  doc/rmessageix.rst
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
  message_ix/reporting/computations.py
  message_ix/tests/data/test_core.R
  rmessageix/.Rbuildignore
  rmessageix/DESCRIPTION
  rmessageix/NAMESPACE
  rmessageix/R/init_rmessageix.R
  rmessageix/README.md
  rmessageix/man/rmessageix.Rd
  rmessageix/tests/testthat.R
  setup.cfg
  tutorial/Austrian_energy_system/R_austria.ipynb
  tutorial/Austrian_energy_system/R_austria_load_scenario.ipynb
Labels: docs, enh

#368 Update Westeros tutorial: firm capacity
  RELEASE_NOTES.rst
  tutorial/README.rst
  tutorial/westeros/_static/firm-capacity.png
  tutorial/westeros/_static/firm-capacity.pptx
  tutorial/westeros/westeros_firm_capacity.ipynb
Labels: docs, enh

#369 Update Westeros tutorial: flexible generation
  RELEASE_NOTES.rst
  tutorial/README.rst
  tutorial/westeros/westeros_flexible_generation.ipynb
Labels: docs

#476 Set .gitattributes for RELEASE_NOTES.rst
  .gitattributes
  .github/workflows/pytest.yaml
  doc/rmessageix.rst
  message_ix/tests/test_tutorials.py
Labels: ci, enh

#370 Add new Westeros tutorial: depicting renewable resource supply curves
  RELEASE_NOTES.rst
  tutorial/README.rst
  tutorial/westeros/_static/renewable_resource_res.png
  tutorial/westeros/_static/renewable_resource_res_exercise.png
  tutorial/westeros/_static/westeros_renewable_resource_potentials.png
  tutorial/westeros/_static/westeros_renewable_resource_potentials.pptx
  tutorial/westeros/_static/westeros_res.pptx
  tutorial/westeros/westeros_renewable_resource.ipynb
Labels: docs
