Repository iiasa/message_ix, pull requests merged in 2021-04, with the labels that each got.

#452 Install GAMS using iiasa/actions for CI
  .github/workflows/nightly.yml
  .github/workflows/pytest.yml
  ci/nightly.yaml
  message_ix/testing/nightly.py
  message_ix/tests/reporting/test_computations.py
  message_ix/tests/test_core.py
  message_ix/tests/test_feature_addon.py
  message_ix/tests/test_feature_bound_activity_shares.py
  message_ix/tests/test_feature_bound_emission.py
  message_ix/tests/test_feature_price_commodity.py
  message_ix/tests/test_feature_price_emission.py
  message_ix/tests/test_feature_storage.py
  message_ix/tests/test_macro.py
  message_ix/tests/tools/test_add_year.py
  message_ix/tests/util/test_tutorial.py
  message_ix/tools/add_year/__init__.py
Labels: ci

#453 Work around Windows CI failures
  .github/workflows/pytest.yml
Labels: ci

#454 Expand docs of dynamic constraint parameters
  RELEASE_NOTES.rst
  doc/contrib/release.rst
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/parameter_def.gms
Labels: docs, enh

#463 Add "publish" CI workflow
  .github/workflows/conda.yaml
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
  doc/conf.py
  doc/contrib/release.rst
  tutorial/README.rst
Labels: ci, enh

#365 Add new Westeros tutorial: Addon technologies
  RELEASE_NOTES.rst
  message_ix/tests/test_tutorials.py
  tutorial/README.rst
  tutorial/westeros/_static/addon_technologies_res.png
  tutorial/westeros/westeros_addon_technologies.ipynb
Labels: docs

#460 Updated macOS specific GAMS installation guidelines
  INSTALL.rst
  RELEASE_NOTES.rst
Labels: docs
