Repository iiasa/message_ix, pull requests merged in 2021-07, with the labels that each got.

#492 Adjust for genno 1.6, pyam 1.0
  .gitignore
  RELEASE_NOTES.rst
  message_ix/reporting/computations.py
  message_ix/tests/test_reporting.py
  tutorial/westeros/westeros_report.ipynb
Labels: ci, docs

#493 Use np.isscalar; improve contributing.rst
  doc/conf.py
  doc/contributing.rst
  message_ix/core.py
Labels: docs, enh

#495 Adjust objective values for nightly test scenarios
  message_ix/tests/data/scenarios.yaml
Labels: ci
