Repository iiasa/message_ix, pull requests merged in 2022-03, with the labels that each got.

#570 Document approx. installation time with conda
  INSTALL.rst
Labels: docs

#568 Address failing copying of GAMS files
  message_ix/cli.py
  message_ix/tests/test_cli.py
Labels: bug

#327 Clean up message_ix.macro
  .github/workflows/publish.yaml
  RELEASE_NOTES.rst
  doc/contributing.rst
  doc/macro.rst
  message_ix/core.py
  message_ix/macro.py
  message_ix/tests/data/multiregion_macro_input.xlsx
  message_ix/tests/data/westeros_macro_input.xlsx
  message_ix/tests/test_macro.py
Labels: macro
