Repository iiasa/message_ix, pull requests merged in 2022-04, with the labels that each got.

#581 Correct index of "time" in equation RENEWABLES_EQUIVALENCE
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/model_core.gms
Labels: bug, timeslice

#586 Adjust .Reporter.get_tasks for genno 1.11
  message_ix/reporting/__init__.py
Labels: reporting

#585 Un-pin message-ix version in Documentation and Conda CI workflow
  .github/pull_request_template.md
  .github/workflows/conda.yaml
  INSTALL.rst
Labels: docs, ci

#524 Extend explanations and update signature of creating data frames in Westeros tutorials
  RELEASE_NOTES.rst
  message_ix/testing/__init__.py
  message_ix/tests/data/westeros_macro_input.xlsx
  message_ix/tests/test_macro.py
  message_ix/tests/test_reporting.py
  message_ix/tests/test_soft_constraints.py
  message_ix/tests/test_tutorials.py
  message_ix/util/__init__.py
  tutorial/westeros/westeros_addon_technologies.ipynb
  tutorial/westeros/westeros_baseline.ipynb
  tutorial/westeros/westeros_baseline_using_xlsx_import_part1.ipynb
  tutorial/westeros/westeros_baseline_using_xlsx_import_part2.ipynb
  tutorial/westeros/westeros_emissions_bounds.ipynb
  tutorial/westeros/westeros_emissions_taxes.ipynb
  tutorial/westeros/westeros_firm_capacity.ipynb
  tutorial/westeros/westeros_flexible_generation.ipynb
  tutorial/westeros/westeros_fossil_resource.ipynb
  tutorial/westeros/westeros_historical_new_capacity.ipynb
  tutorial/westeros/westeros_renewable_resource.ipynb
  tutorial/westeros/westeros_report.ipynb
  tutorial/westeros/westeros_seasonality.ipynb
  tutorial/westeros/westeros_share_constraint.ipynb
  tutorial/westeros/westeros_soft_constraints.ipynb
Labels: docs
