Repository iiasa/message_ix, pull requests merged in 2022-01, with the labels that each got.

#520 Expanding the documentation with an outlook of the MESSAGEix usage
  NOTICE.rst
  RELEASE_NOTES.rst
  doc/_static/usage_figures/1-s2.0-S2210670721005333-gr19_lrg.jpg
  doc/_static/usage_figures/10.1016-j.scs.2021.103257.jpg
  doc/_static/usage_figures/10.1038-s41560-018-0172-6.webp
  doc/_static/usage_figures/10.1038-s41560-018-0179-z.webp
  doc/_static/usage_figures/10.3390-en12081483.png
  doc/_static/usage_figures/41560_2021_904.webp
  doc/conf.py
  doc/contributing.rst
  doc/index.rst
  doc/references.bib
  doc/sharing.rst
  doc/usage.rst
Labels: docs, discuss

#539 Remove extras_require genno[plotnine]
  setup.cfg
Labels: enh

#509 Enhance mathematical formulation to treat sub-annual time slices consistently
  RELEASE_NOTES.rst
  doc/time.rst
  message_ix/model/MESSAGE/data_load.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
  message_ix/model/includes/period_parameter_assignment.gms
  message_ix/models.py
  message_ix/tests/test_feature_temporal_level.py
  message_ix/tests/test_reporting.py
  message_ix/tests/test_tutorials.py
Labels: enh, timeslice

#541 Address failing "Install from conda-forge" workflow
  .github/workflows/conda.yaml
Labels: ci

#551 Adjust declaration of time_relative(time)
  message_ix/model/MESSAGE/sets_maps_def.gms
Labels: bug
