Repository iiasa/message_ix, pull requests merged in 2022-05, with the labels that each got.

#595 Extend documentation of `CAP` and `CAP_NEW`
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/model_core.gms
Labels: enh, docs

#594 Extend documentation to guide users through Westeros tutorials
  RELEASE_NOTES.rst
  tutorial/README.rst
  tutorial/westeros/westeros_baseline.ipynb
Labels: docs

#597 Add new logo and diagram to Sphinx/RTD docs
  RELEASE_NOTES.rst
  doc/_static/IIASA_logo.png
  doc/_static/combined-logo-white.svg
  doc/_static/iiasa-logo-white.svg
  doc/_static/ix_features.png
  doc/_static/ix_features.svg
  doc/_static/logo_white.png
  doc/_static/messageix-community-logo-white.svg
  doc/_static/messageix-community-logo.svg
  doc/_static/messageix-favicon.svg
  doc/_static/messageix-logo-white.svg
  doc/_static/messageix-logo.svg
  doc/conf.py
  doc/index.rst
Labels: enh, docs

#598 Extend documentation on historical capacity and activity values
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/parameter_def.gms
Labels: enh, docs

#572 Extend feature vintage_and_active_years()
  .github/workflows/pytest.yaml
  .gitignore
  RELEASE_NOTES.rst
  doc/api.rst
  message_ix/core.py
  message_ix/tests/test_core.py
  message_ix/tests/test_feature_vintage_and_active_years.py
Labels: enh

#613 Ensure MESSAGE.enforce() runs for MESSAGE_MACRO
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  message_ix/models.py
  pyproject.toml
Labels: bug, macro
