Repository iiasa/message_ix, pull requests merged in 2022-09, with the labels that each got.

#645 Add additional oscillation indicator
  RELEASE_NOTES.rst
  doc/macro.rst
  message_ix/model/MESSAGE-MACRO_run.gms
  message_ix/models.py
Labels: enh

#649 Work around CI failure due to plotnine
  .github/workflows/conda.yaml
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
  RELEASE_NOTES.rst
  pyproject.toml
Labels: ci

#650 Specify Python version for "nightly" CI workflow
  .github/workflows/nightly.yaml
  .github/workflows/pytest.yaml
Labels: ci

#656 Adjust `.macro.Calculate._bconst` for pandas 1.5.0
  RELEASE_NOTES.rst
  doc/api.rst
  doc/conf.py
  doc/contrib/tutorial.rst
  doc/contrib/version.rst
  message_ix/core.py
  message_ix/macro.py
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/models.py
Labels: bug, macro

#648 Correct calculation of COST_NODAL_NET for standalone MESSAGE
  RELEASE_NOTES.rst
  doc/conf.py
  doc/macro.rst
  doc/references.bib
  message_ix/model/MACRO/macro_calibration.gms
  message_ix/model/MESSAGE/model_solve.gms
  message_ix/tests/data/westeros_macro_input.xlsx
  message_ix/tests/test_macro.py
Labels: bug
