Repository iiasa/message_ix, pull requests merged in 2022-02, with the labels that each got.

#556 Adjust files to new black release
  message_ix/macro.py
  message_ix/testing/__init__.py
  message_ix/tests/test_cli.py
Labels: ci

#557 Read GAMS CPLEX solver options for MESSAGE from user config
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
  RELEASE_NOTES.rst
  doc/api.rst
  doc/time.rst
  message_ix/__init__.py
  message_ix/models.py
  message_ix/tests/test_tutorials.py
  setup.cfg
Labels: enh

#567 Add Reporter.add_tasks()
  RELEASE_NOTES.rst
  message_ix/reporting/__init__.py
Labels: enh, reporting
