Repository iiasa/message_ix, pull requests merged in 2022-11, with the labels that each got.

#664 Adjust "ureg" test fixture for pint 0.20
  message_ix/tests/conftest.py
Labels: ci

#665 Miscellaneous CI updates for 2022-W44
  .github/workflows/conda.yaml
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
Labels: ci

#666 Exclude Python 3.11 from CI
  .github/workflows/lint.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish.yaml
  .github/workflows/pytest.yaml
Labels: ci

#654 Correct calculation of NEW_CAPACITY_CONSTRAINTs
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/model_core.gms
  message_ix/testing/__init__.py
  message_ix/tests/test_equation_NEW_CAPACITY_CONTRAINT.py
Labels: bug

#653 Correct levelized_cost calculation
  RELEASE_NOTES.rst
  doc/macro.rst
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/model/MESSAGE/scaling_investment_costs.gms
Labels: bug

#633 Enhancing storage equations by considering `mode` and `lvl_temporal`
  RELEASE_NOTES.rst
  doc/api.rst
  message_ix/model/MESSAGE/data_load.gms
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
  message_ix/models.py
  message_ix/tests/test_feature_storage.py
  message_ix/tests/test_reporting.py
  message_ix/tests/test_tutorials.py
  message_ix/util/__init__.py
Labels: enh, timeslice
