Repository iiasa/message_ix, pull requests merged in 2023-11, with the labels that each got.

#748 Include dependabot configuration file
  .github/dependabot.yml
Labels: enh, ci

#756 Reduce number of dependabot PRs
  .github/dependabot.yml
Labels: docs, ci, dependencies

#761 Rename 'report'
  .github/workflows/pytest.yaml
  .gitignore
  INSTALL.rst
  RELEASE_NOTES.rst
  doc/api.rst
  doc/conf.py
  doc/contrib/tutorial.rst
  doc/contributing.rst
  doc/macro.rst
  doc/reporting.rst
  message_ix/__init__.py
  message_ix/core.py
  message_ix/macro.py
  message_ix/model/MESSAGE/model_core.gms
  message_ix/models.py
  message_ix/report/__init__.py
  message_ix/report/operator.py
  message_ix/report/pyam.py
  message_ix/reporting/__init__.py
  message_ix/tests/report/test_operator.py
  message_ix/tests/test_feature_storage.py
  message_ix/tests/test_macro.py
  message_ix/tests/test_models.py
  message_ix/tests/test_report.py
  message_ix/tests/test_soft_constraints.py
  message_ix/tests/test_tutorials.py
  message_ix/tests/util/test_tutorial.py
  message_ix/tools/add_year/__init__.py
  message_ix/util/__init__.py
  message_ix/util/tutorial.py
  pyproject.toml
  tutorial/Austrian_energy_system/austria.ipynb
  tutorial/Austrian_energy_system/austria_load_scenario.ipynb
  tutorial/Austrian_energy_system/austria_multiple_policies-answers.ipynb
  tutorial/Austrian_energy_system/austria_multiple_policies.ipynb
  tutorial/Austrian_energy_system/austria_single_policy.ipynb
  tutorial/README.rst
  tutorial/westeros/westeros_addon_technologies.ipynb
  tutorial/westeros/westeros_baseline.ipynb
  tutorial/westeros/westeros_emissions_bounds.ipynb
  tutorial/westeros/westeros_firm_capacity.ipynb
  tutorial/westeros/westeros_flexible_generation.ipynb
  tutorial/westeros/westeros_fossil_resource.ipynb
  tutorial/westeros/westeros_historical_new_capacity.ipynb
  tutorial/westeros/westeros_renewable_resource.ipynb
  tutorial/westeros/westeros_report.ipynb
  tutorial/westeros/westeros_seasonality.ipynb
  tutorial/westeros/westeros_share_constraint.ipynb
  tutorial/westeros/westeros_soft_constraints.ipynb
Labels: enh, reporting

#704 Integration of LPdiag tool
  .gitignore
  RELEASE_NOTES.rst
  doc/tools/lp_diag.rst
  message_ix/cli.py
  message_ix/tests/data/lp_diag/aez.mps
  message_ix/tests/data/lp_diag/diet.mps
  message_ix/tests/data/lp_diag/error_bounds_string_short.mps
  message_ix/tests/data/lp_diag/error_bounds_too_short.mps
  message_ix/tests/data/lp_diag/error_bounds_type_not_needed.mps
  message_ix/tests/data/lp_diag/error_bounds_unknown_type.mps
  message_ix/tests/data/lp_diag/error_coefficient_string_long.mps
  message_ix/tests/data/lp_diag/error_coefficient_string_short.mps
  message_ix/tests/data/lp_diag/error_err_tst.mps
  message_ix/tests/data/lp_diag/error_ranges_string_long.mps
  message_ix/tests/data/lp_diag/error_ranges_string_short.mps
  message_ix/tests/data/lp_diag/error_ranges_too_short.mps
  message_ix/tests/data/lp_diag/error_rhs_string_long.mps
  message_ix/tests/data/lp_diag/error_rhs_string_short.mps
  message_ix/tests/data/lp_diag/error_rhs_too_short.mps
  message_ix/tests/data/lp_diag/error_sections_all.mps
  message_ix/tests/data/lp_diag/error_sections_optional_order.mps
  message_ix/tests/data/lp_diag/error_sections_required_order.mps
  message_ix/tests/data/lp_diag/error_sections_too_many.mps
  message_ix/tests/data/lp_diag/error_sections_unknown.mps
  message_ix/tests/data/lp_diag/jg_korh.mps
  message_ix/tests/data/lp_diag/lotfi.mps
  message_ix/tests/tools/__init__.py
  message_ix/tests/tools/test_lp_diag.py
  message_ix/tools/lp_diag/__init__.py
  message_ix/tools/lp_diag/cli.py
  pyproject.toml
Labels: enh
