Repository iiasa/message_ix, pull requests merged in 2024-03, with the labels that each got.

#784 Make tests robust & independent
  .github/workflows/pytest.yaml
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  conftest.py
  doc/api.rst
  doc/contributing.rst
  message_ix/cli.py
  message_ix/report/operator.py
  message_ix/testing/__init__.py
  message_ix/testing/nightly.py
  message_ix/tests/test_cli.py
  message_ix/tests/test_core.py
  message_ix/tests/test_feature_bound_activity_shares.py
  message_ix/tests/test_feature_capacity_factor.py
  message_ix/tests/test_feature_price_emission.py
  message_ix/tests/test_feature_storage.py
  message_ix/tests/test_feature_temporal_level.py
  message_ix/tests/test_integration.py
  message_ix/tests/test_legacy_version.py
  message_ix/tests/test_macro.py
  message_ix/tests/test_nightly.py
  message_ix/tests/tools/test_add_year.py
  message_ix/tools/add_year/__init__.py
  message_ix/tools/add_year/cli.py
  message_ix/util/__init__.py
  pyproject.toml
Labels: ci

#798 Update Westeros multinode tutorial for hints
  .github/workflows/pytest.yaml
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  message_ix/tests/test_tutorials.py
  tutorial/README.rst
  tutorial/westeros/westeros_multinode_energy_trade.ipynb
Labels: docs

#805 Introduce some additional labels in docs
  INSTALL.rst
Labels: docs

#809 Housekeeping for 2024-W13
  .github/workflows/pytest.yaml
  .pre-commit-config.yaml
  doc/api.rst
  doc/conf.py
  doc/contrib/tutorial.rst
  message_ix/core.py
  message_ix/macro.py
  message_ix/report/operator.py
  message_ix/report/pyam.py
  message_ix/testing/__init__.py
  message_ix/tests/test_feature_duration_time.py
  message_ix/tools/add_year/__init__.py
  message_ix/util/__init__.py
  pyproject.toml
Labels: enh, ci
