Repository iiasa/message_ix, pull requests merged in 2024-01, with the labels that each got.

#765 Record message_ix version in scenario data & GDX
  .github/workflows/pytest.yaml
  README.md
  RELEASE_NOTES.rst
  doc/api.rst
  doc/conf.py
  message_ix/macro.py
  message_ix/model/MESSAGE/data_load.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
  message_ix/models.py
  message_ix/report/__init__.py
  message_ix/testing/__init__.py
  message_ix/tests/conftest.py
  message_ix/tests/data/report-pyam-write.csv
  message_ix/tests/test_cli.py
  message_ix/tests/test_core.py
  message_ix/tests/test_equation_NEW_CAPACITY_CONSTRAINT.py
  message_ix/tests/test_equation_NEW_CAPACITY_CONTRAINT.py
  message_ix/tests/test_feature_bound_activity_shares.py
  message_ix/tests/test_feature_price_emission.py
  message_ix/tests/test_integration.py
  message_ix/tests/test_macro.py
  message_ix/tests/test_soft_constraints.py
  message_ix/tests/test_tutorials.py
  message_ix/util/tutorial.py
  pyproject.toml
Labels: enh

#783 Update minimum version of genno
  RELEASE_NOTES.rst
  pyproject.toml
Labels: enh

#785 Save minutes by avoiding duplicate test runs
  .github/workflows/pytest.yaml
Labels: ci

#789 Update tests
  .github/workflows/nightly.yaml
  .github/workflows/pytest.yaml
  message_ix/tests/test_core.py
Labels: bug, ci
