Repository iiasa/message_ix, pull requests merged in 2024-07, with the labels that each got.

#863 Bump GAMS version in CI workflows to adjust for ixmp changes
  .github/workflows/nightly.yaml
  .github/workflows/pytest.yaml
Labels: ci

#864 Adjust for mypy 1.11
  message_ix/report/__init__.py
  message_ix/report/operator.py
  message_ix/report/pyam.py
  message_ix/tests/report/test_operator.py
  tutorial/westeros/genno.svg
  tutorial/westeros/westeros_report.ipynb
Labels: ci, tutorials

#865 Adjust to RTD's upcoming addon changes
  doc/conf.py
Labels: docs

#870 Migrate issue templates to forms
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/other.yml
Labels: enh
