Repository iiasa/message_ix, pull requests merged in 2025-05, with the labels that each got.

#894 Test against ixmp4
  .github/workflows/pytest.yaml
  RELEASE_NOTES.rst
  ci/rtd-requirements.txt
  message_ix/core.py
  message_ix/model/includes/period_parameter_assignment.gms
  message_ix/models.py
  message_ix/testing/__init__.py
  message_ix/tests/data/reportergraph.txt
  message_ix/tests/data/reporterixgraph.txt
  message_ix/tests/model/test_message.py
  message_ix/tests/report/test_operator.py
  message_ix/tests/test_cli.py
  message_ix/tests/test_core.py
  message_ix/tests/test_feature_addon.py
  message_ix/tests/test_feature_bound_activity_shares.py
  message_ix/tests/test_feature_bound_emission.py
  message_ix/tests/test_feature_capacity_factor.py
  message_ix/tests/test_feature_duration_time.py
  message_ix/tests/test_feature_price_commodity.py
  message_ix/tests/test_feature_price_emission.py
  message_ix/tests/test_feature_storage.py
  message_ix/tests/test_feature_temporal_level.py
  message_ix/tests/test_feature_vintage_and_active_years.py
  message_ix/tests/test_integration.py
  message_ix/tests/test_legacy_version.py
  message_ix/tests/test_macro.py
  message_ix/tests/test_models.py
  message_ix/tests/test_report.py
  message_ix/tests/test_snapshots.py
  message_ix/tests/test_testing.py
  message_ix/tests/test_tutorials.py
  message_ix/tests/tools/test_add_year.py
  message_ix/tests/tools/test_lp_diag.py
  message_ix/tests/tools/test_migrate.py
  message_ix/tests/tools/test_sankey.py
  message_ix/tests/util/test_gams_io.py
  message_ix/tests/util/test_ixmp4.py
  message_ix/tests/util/test_sphinx_gams.py
  message_ix/tests/util/test_tutorial.py
  message_ix/util/__init__.py
  message_ix/util/gams_io.py
  message_ix/util/ixmp4.py
  message_ix/util/scenario_data.py
  message_ix/util/scenario_setup.py
  pyproject.toml
  tutorial/westeros/westeros_emissions_taxes.ipynb
  tutorial/westeros/westeros_report.ipynb
Labels: enh, IXMP4Backend

#808 Add an option to solve MACRO concurrently for all regions
  RELEASE_NOTES.rst
  doc/api.rst
  message_ix/model/MACRO/macro_solve.gms
  message_ix/model/MACRO/setup.gms
  message_ix/model/MACRO_run.gms
  message_ix/model/MESSAGE-MACRO_run.gms
  message_ix/model/MESSAGE_master.gms
  message_ix/models.py
  message_ix/tests/test_macro.py
Labels: enh, macro, safe to test

#946 Quiet logging from MESSAGE.initialize
  RELEASE_NOTES.rst
  message_ix/models.py
  message_ix/tests/test_models.py
Labels: bug, IXMP4Backend
