Repository iiasa/message_ix, pull requests merged in 2025-04, with the labels that each got.

#924 Fix historic vintages in map_tec_lifetime
  RELEASE_NOTES.rst
  doc/conf.py
  message_ix/model/MESSAGE/data_load.gms
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/model/MESSAGE/sets_maps_def.gms
  message_ix/testing/__init__.py
  message_ix/tests/model/__init__.py
  message_ix/tests/model/test_message.py
  message_ix/tests/test_equation_NEW_CAPACITY_CONSTRAINT.py
  message_ix/tests/test_macro.py
  message_ix/tests/test_report.py
  message_ix/tests/test_soft_constraints.py
  message_ix/tests/test_testing.py
  message_ix/tests/test_util.py
Labels: bug, gams

#926 Document duration_period_sum and its use
  RELEASE_NOTES.rst
  doc/conf.py
  message_ix/model/MACRO/macro_solve.gms
  message_ix/model/MESSAGE/parameter_def.gms
Labels: docs, macro, gams

#935 Adjust GAMS expression for type_tec_{share,total}
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/data_load.gms
Labels: gams

#936 Use Zenodo snapshots for nightly scenario tests
  .github/workflows/nightly.yaml
  RELEASE_NOTES.rst
  ci/nightly.yaml
  doc/conf.py
  doc/tools/migrate.rst
  message_ix/model/MESSAGE/parameter_def.gms
  message_ix/testing/__init__.py
  message_ix/testing/nightly.py
  message_ix/tests/conftest.py
  message_ix/tests/data/scenarios.yaml
  message_ix/tests/report/test_operator.py
  message_ix/tests/test_feature_capacity_factor.py
  message_ix/tests/test_feature_temporal_level.py
  message_ix/tests/test_nightly.py
  message_ix/tests/test_report.py
  message_ix/tests/test_snapshots.py
  message_ix/tests/tools/test_migrate.py
  message_ix/tools/migrate.py
  pyproject.toml
Labels: enh, ci, python
