Repository iiasa/message_ix, pull requests merged in 2025-01, with the labels that each got.

#770 Add `.tools.sankey` and tutorial
  RELEASE_NOTES.rst
  doc/api.rst
  doc/conf.py
  doc/reporting.rst
  doc/tools/sankey.rst
  message_ix/report/__init__.py
  message_ix/tests/test_report.py
  message_ix/tests/test_tutorials.py
  message_ix/tests/tools/test_sankey.py
  message_ix/tools/sankey.py
  pyproject.toml
  tutorial/README.rst
  tutorial/westeros/westeros_sankey.ipynb
Labels: enh, safe to test

#905 Fix workflow runs from forks
  .github/workflows/pytest.yaml
Labels: ci

#909 Run "pytest" GHA workflow on pull_request_target
  .github/workflows/pytest.yaml
  .github/workflows/receive.yaml
Labels: ci

#911 Clean up CI & miscellaneous updates for 3.10
  .github/workflows/pytest.yaml
  .pre-commit-config.yaml
  README.md
  RELEASE_NOTES.rst
  doc/conf.py
  doc/index.rst
  message_ix/model/MESSAGE-MACRO_run.gms
  message_ix/model/MESSAGE_master.gms
  message_ix/model/MESSAGE_run.gms
  message_ix/model/includes/copyright.gms
  pyproject.toml
Labels: enh, docs, ci
