Repository iiasa/message_ix, pull requests merged in 2025-02, with the labels that each got.

#888 Update docs with links and a new paper
  doc/_static/usage_figures/1-s2.0-S2352152X2400834X-gr1.jpg
  doc/contributing.rst
  doc/references.bib
  doc/usage.rst
Labels: docs, safe to test

#912 Fix `PRICE_EMISSION` definition
  RELEASE_NOTES.rst
  message_ix/model/MESSAGE/data_load.gms
  message_ix/model/MESSAGE/model_core.gms
  message_ix/model/MESSAGE/model_solve.gms
  message_ix/models.py
  message_ix/tests/test_feature_price_emission.py
  message_ix/tests/test_report.py
  message_ix/tests/test_tutorials.py
  tutorial/westeros/westeros_emissions_taxes.ipynb
Labels: bug, safe to test

#915 Adjust links to MESSAGEix-GLOBIOM docs
  doc/conf.py
  doc/macro.rst
Labels: docs

#918 Fix "install from conda forge" CI after ixmp release v3.10.0
  .github/workflows/conda.yaml
Labels: ci
